-- Roadmap seed: the history of the CRM so far (shipped), what is being built
-- now, and what is planned or being explored. Idempotent: only runs while the
-- table is still empty, so re-running never duplicates and never overwrites
-- edits a SuperAdmin has made on the Roadmap page.
--
-- Columns of the VALUES list: title, area, description, status, target,
-- shipped_on ('' = none), sort_order.

insert into public.roadmap_items (title, area, description, status, target, shipped_on, sort_order)
select v.title, nullif(v.area, ''), nullif(v.description, ''), v.status, nullif(v.target, ''),
       nullif(v.shipped_on, '')::date, v.sort_order::int
from (values
  -- ---------------------------------------------------------------- SHIPPED
  ('Prestige Legacy CRM goes live', 'Foundation',
   'The first version of the CRM was launched with secure sign-in, your own branded Prestige Legacy look and a shared app layout with a sidebar. Every agent signs in with their own account and only sees what their role allows.',
   'shipped', '', '2026-08-27', '10'),
  ('Dashboard', 'Dashboard',
   'A home screen that shows your leads, follow-ups and performance at a glance when you sign in.',
   'shipped', '', '2026-08-27', '20'),
  ('Leads Manager and Lead Detail', 'Leads',
   'One place to keep all your prospects. Add, search and filter leads, open a lead to see its full profile, notes and history, and edit details at any time.',
   'shipped', '', '2026-08-27', '30'),
  ('Sales Pipeline', 'Pipeline',
   'A board that shows every lead by stage, from new to closed. Drag a lead card to the next stage (or pick the stage from a dropdown) so you always know who needs your attention next.',
   'shipped', '', '2026-08-27', '40'),
  ('My Team and Group Manager view', 'Team',
   'Managers can see their agents and units in one place, and drill down from a Group Manager to the people underneath.',
   'shipped', '', '2026-08-27', '50'),
  ('WA Flow scripts', 'WhatsApp',
   'Ready-made WhatsApp messages for every step of following up a lead. Pick a script, fill in the lead''s name automatically and send it straight from the CRM.',
   'shipped', '', '2026-08-27', '60'),
  ('Statistics', 'Statistics',
   'Charts and numbers that show how many leads you have, how they move through the pipeline and how you are performing.',
   'shipped', '', '2026-08-27', '70'),
  ('Security and data-access review', 'Security',
   'A full check of who can read and change what. Several gaps were closed so that each agent only sees their own leads and their downline''s, and every action that saves data now reports failures clearly.',
   'shipped', '', '2026-08-28', '80'),
  ('Quotation calculators inside the CRM', 'Quotations',
   'The agency''s quotation calculators now open inside the CRM, pre-filled with the lead''s details. Sending a quotation over WhatsApp marks the lead as quoted automatically.',
   'shipped', '', '2026-08-28', '90'),
  ('Settings, roles and user management', 'Settings',
   'The SuperAdmin can add and edit people, set roles (Group Manager, Unit Manager, Aspirant Unit Manager, Agent), set monthly targets and force a password reset. Passwords and invitations are sent by email.',
   'shipped', '', '2026-08-28', '100'),
  ('Phone-friendly screens', 'Mobile',
   'Every screen was checked on a phone and fixed where it broke, so the CRM is comfortable to use on the go.',
   'shipped', '', '2026-08-28', '110'),
  ('Fuller lead details and Google Sheets import', 'Leads',
   'Leads now keep postcode, state, source, occupation class, gender, smoker status, remarks and potential value. You can also bring in a whole list of leads from a Google Sheet in one go.',
   'shipped', '', '2026-08-29', '120'),
  ('Aspirant Unit Manager role and team hierarchy', 'Team',
   'A new rank for people growing into Unit Managers, with leads assigned by rank and a clearer tree from Group Manager down to agent.',
   'shipped', '', '2026-08-30', '130'),
  ('Quotation Customizer and saved quotations', 'Quotations',
   'Build a custom comparison quotation for a client, export it as a one-page PDF or image, send it on WhatsApp and save it on the lead. Saving again updates the existing quotation instead of creating duplicates, and you can edit or delete quotations in bulk.',
   'shipped', '', '2026-09-05', '140'),
  ('Invite agents and recruit by link', 'Team',
   'Invite a new agent by email or share the invite straight to WhatsApp. You can also share a recruitment link: people apply, and a manager approves them before they get in.',
   'shipped', '', '2026-09-05', '150'),
  ('Set Target for everyone', 'Team',
   'Every role can set monthly targets for themselves and the people under them. Leads are only handed out to people marked active.',
   'shipped', '', '2026-09-05', '160'),
  ('Appointments and notifications', 'Appointments',
   'Book appointments with leads, see them in a calendar, move the lead to the Appointment stage and get a notification bell for what needs attention today.',
   'shipped', '', '2026-09-06', '170'),
  ('WA Flow board and lead rebalancing', 'WhatsApp',
   'A board view of WhatsApp follow-ups, a WhatsApp card on each lead, and a way to rebalance leads between agents when someone has too many.',
   'shipped', '', '2026-09-06', '180'),
  ('Lead Generation: agent landing pages', 'Lead Generation',
   'Each agent gets a personal landing page with a built-in page builder. Prospects fill in a form and land in your leads. Includes QuickQuote forms and a long Medical Card funnel, and can connect to outside tools for automation.',
   'shipped', '', '2026-09-07', '190'),
  ('Closing scripts library', 'WhatsApp',
   'Libraries of closing scripts with their own sidebar menu, also available right inside a lead so you can copy the right words at the right moment.',
   'shipped', '', '2026-09-09', '200'),
  ('Safe deletes and recoverable leads', 'Leads',
   'Deleting a lead, user or export now always asks you to confirm. Deleted leads are kept aside instead of vanishing so mistakes can be undone. All dates follow Malaysia time.',
   'shipped', '', '2026-09-09', '210'),
  ('Dashboard goal tracking and daily scoreboard', 'Dashboard',
   'See your ANC goal and whether you are on pace, a daily approach scoreboard, a Needs follow-up card, a live clock and widgets you can show or hide.',
   'shipped', '', '2026-09-11', '220'),
  ('Statistics for you and your team', 'Statistics',
   'Personal performance numbers, plus drill-down into any agent or unit you are allowed to see.',
   'shipped', '', '2026-09-11', '230'),
  ('Case submission and My Sales', 'My Sales',
   'When a client signs, submit the case with their details, nominee, benefits and certificate. Cases get proper lead numbers and feed straight into your sales figures.',
   'shipped', '', '2026-09-13', '240'),
  ('Servicing and contribution tracking', 'Servicing',
   'After a sale, see which clients are due to pay, who is overdue and what has been collected. Includes a JomPay reminder and a servicing view for each client.',
   'shipped', '', '2026-09-13', '250'),
  ('ANC from signed cases', 'Dashboard',
   'The dashboard now counts ANC from real signed cases, shows Inforced and Collected figures, and uses the actual closing date of the certificate. Yearly and Monthly Target cards are clearer.',
   'shipped', '', '2026-09-14', '260'),
  ('Client portal (Sijil)', 'Client Portal',
   'Clients get their own page to view their certificates. They sign in with their NRIC, see multiple certificates as cards, and see how much is due and when. Each client only ever sees their own.',
   'shipped', '', '2026-09-15', '270'),
  ('My Profile and plan categories', 'Settings',
   'A My Profile tab for your own details and landing page images, plus plan categories, a personal dashboard and two client guides you can share.',
   'shipped', '', '2026-09-16', '280'),
  ('Speed and security hardening', 'Performance',
   'Pages load faster thanks to database tuning, and extra protection was added against common web attacks. Sign-in checks became quicker and permission checks run once per request instead of once per row.',
   'shipped', '', '2026-09-24', '290'),
  ('Client portal: WhatsApp agent and payment help', 'Client Portal',
   'A button for clients to message their agent, clear payment instructions and benefit descriptions.',
   'shipped', '', '2026-09-27', '300'),
  ('Manage Cases', 'My Sales',
   'A page to review all submitted cases. Click a case to see its full detail, and managers see cases across their team.',
   'shipped', '', '2026-09-27', '310'),
  ('Top-level menus and Training link', 'Navigation',
   'Agent landing pages, servicing and other main areas now have their own menus, and a Training link in the sidebar.',
   'shipped', '', '2026-09-27', '320'),
  ('Branding: insurer logo and cover image', 'Branding',
   'The SuperAdmin can upload the insurer logo and a header cover image that appear on every agent landing page.',
   'shipped', '', '2026-09-27', '330'),
  ('App-like mobile experience', 'Mobile',
   'The phone version feels like a real app: a menu drawer, swipeable dashboard cards, swipe to delete a lead, modals instead of long pages, a welcome message at login and no more accidental Sign Out.',
   'shipped', '', '2026-09-28', '340'),
  ('Birthday and contribution alerts in notifications', 'Notifications',
   'The notification bell now also shows upcoming birthdays, contributions due soon and overdue contributions, so you can reach out at the right time.',
   'shipped', '', '2026-09-28', '350'),
  ('Team leaderboard and org chart', 'Team',
   'Managers see a ranked leaderboard of this year''s inforced ANC, and an organisation chart view of the team. The SuperAdmin can view the leaderboard but is never ranked on it.',
   'shipped', '', '2026-09-28', '360'),
  ('System colour selector', 'Branding',
   'The SuperAdmin can choose the colour of the whole CRM: Prestige Blue, Great Eastern Red or a custom colour, with a live preview and a warning for colours that are too light to read.',
   'shipped', '', '2026-10-01', '370'),
  ('Simple Medical Card quotation', 'Quotations',
   'A simpler quotation sheet for Medical Card that compares two options side by side with riders, in English or Bahasa Malaysia, and exports as PDF or image.',
   'shipped', '', '2026-10-01', '380'),
  ('Sticky sidebar', 'Navigation',
   'On desktop, the sidebar stays on screen while a long page scrolls, so the menu and Sign Out are always at hand.',
   'shipped', '', '2026-10-01', '390'),

  -- ------------------------------------------------------------ IN PROGRESS
  ('Support tickets', 'Support',
   'Raise a ticket from inside the CRM when something is wrong or you need help, and follow the reply in one place.',
   'in_progress', '', '', '10'),
  ('What''s new (changelog)', 'Support',
   'A page that lists what has changed in the CRM, so you always know about new features.',
   'in_progress', '', '', '20'),
  ('Roadmap', 'Support',
   'This page: what has shipped, what is being built and what is coming next. Only the SuperAdmin can edit it.',
   'in_progress', '', '', '30'),

  -- ---------------------------------------------------------------- PLANNED
  ('Block deactivated agents from signing in', 'Security',
   'Today, switching an agent to inactive stops leads going to them but does not stop them signing in. Deactivated agents will be locked out at login.',
   'planned', 'Q4 2026', '', '10'),
  ('Membership subscription with CHIP', 'Billing',
   'Take membership payments through the CHIP payment gateway so subscriptions are collected and tracked automatically.',
   'planned', 'Q4 2026', '', '20'),
  ('Automatic birthday and contribution reminders on WhatsApp', 'WhatsApp',
   'Birthdays and contributions are shown in the CRM today. The next step is to send the reminders to clients on WhatsApp for you.',
   'planned', 'Q4 2026', '', '30'),
  ('Tighter access to targets for managers', 'Security',
   'Review exactly which targets each manager can read, so people only see targets of their own downline.',
   'planned', 'Q4 2026', '', '40'),
  ('Charts and emails that follow the system colour', 'Branding',
   'The system colour now covers menus and buttons. Charts and emails sent by the CRM will follow it too.',
   'planned', 'Q1 2027', '', '50'),
  ('Quotation PDF branding', 'Quotations',
   'Put the agency''s logo and colours on exported quotation PDFs so they look consistent with the rest of the CRM.',
   'planned', 'Q1 2027', '', '60'),
  ('Floating bottom tab bar on iPhone', 'Mobile',
   'An iOS-style floating tab bar at the bottom of the phone screen for the main areas.',
   'planned', 'Q1 2027', '', '70'),
  ('Support ticket response targets (SLAs)', 'Support',
   'Show how quickly each ticket should be answered and flag the ones that are running late.',
   'planned', 'Q1 2027', '', '80'),

  -- -------------------------------------------------------------- EXPLORING
  ('Phone and tablet visual test suite', 'Quality',
   'Automatic screenshots of key pages on phone and tablet sizes, so layout problems are caught before they reach you.',
   'exploring', '', '', '10')
) as v(title, area, description, status, target, shipped_on, sort_order)
where not exists (select 1 from public.roadmap_items);
